# Puerto
server.port=8107

# Neon DB PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-square-wave-aqboqoo8-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require&connect_timeout=10
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2SU5QKPpEMtn
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP - Neon DB config
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.jackson.serialization.fail-on-empty-beans=false